<a href="https://colab.research.google.com/github/tomov/VGDL-fMRI-Python-Data-Analysis/blob/master/fMRI_analysis_jiajia/colab_searchlight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Searchlights <a name="searchlights"></a>
[Contributions](#contributions)

In univariate analyses there is a distinction between whole-brain and [ROI-based](https://doi.org/10.1093/scan/nsm006) analyses. When done correctly, whole-brain univariate analyses allow you to identify, in an unbiased and data-driven way, regions of the brain that differ between experimental conditions. Compare this to what we have done with multivariate classification: up to this point we have taken ROIs (e.g., FFA, PPA, even the whole brain) and looked at the pattern of activity across voxels. Using these procedures we have been able to determine whether these voxels collectively contain information about different conditions. However, throughout these analyses it has been unclear whether a subset of these voxels have been driving classification accuracy. Although we could use the weights to indicate which voxels are important, weights alone do not always convey the influence of individual voxels. In other words, we have been unable to say with certainty *where* in the brain there are representations that distinguish between conditions. 

A searchlight is a spatial moving window that exhaustively searches the brain in order to localize representations. Running a searchlight is computationally intensive because it involves running a separate multivariate analysis for every voxel in the brain. Imagine doing your feature selection, hyper-parameter optimization, and cross-validation 100,000 times or more. Fortunately, [BrainIAK](http://brainiak.org/) contains a procedure that efficiently carves up brain data into appropriate chunks and distributes them across the computational resources available.

For more information on the searchlight technique, read this comprehensive [NeuroImage Comment](https://doi.org/10.1016/j.neuroimage.2013.03.041), that also includes citations to landmark papers on the topic. The validity of using searchlights is explained [here](https://doi.org/10.1073/pnas.0600244103).
 
**Pre-requisites:** Familiarity with data loading and classification, notebooks 1-5.

## Goal of this script

1. Learn how to perform a whole-brain searchlight.  
2. Learn how to replace the kernel used inside the searchlight.  
3. Use batch scripts, SLURM, and MPI to run searchlight on compute clusters.
4. Run searchlight on a face-scene dataset.

## Table of contents

>1. [Searchlight workflow](#sl_wf)  
>>1.1 [Data preparation](#data_prep)  
>>1.2 [Executing the searchlight workflow](#exe_wf)   
>>1.3 [Executing on multiple subjects](#multi_subj)
>2. [Running searchlight analyses on a cluster](#submitting_searchlights)  
>>2.1 [Distributing jobs with parallel computing](#ranks)

> 4.Exercises
>[1](#ex1)   [2](#ex2)  [3](#ex3)  [4](#ex4)  [5](#ex5)  [6](#ex6)  [7](#ex7)  [8](#ex8)  [9](#ex9) [10](#ex10) [11](#ex11) [12](#ex12)


In [6]:
!pip install deepdish ipython matplotlib nilearn notebook pandas seaborn watchdog
!pip install pip\<10
!pip install -U git+https://github.com/brainiak/brainiak
!git clone https://github.com/brainiak/brainiak-tutorials.git
!cd brainiak-tutorials/tutorials/; cp -r 07-searchlight 09-fcma 13-real-time utils.py setup_environment.sh /content/
!mkdir /root/brainiak_datasets

  Cloning https://github.com/brainiak/brainiak to /tmp/pip-kp_rdv_2-build
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Requirement already up-to-date: cython in /usr/local/lib/python3.6/dist-packages (from brainiak==0.11.dev9+g7614892)
Requirement already up-to-date: mpi4py>=3 in /usr/local/lib/python3.6/dist-packages (from brainiak==0.11.dev9+g7614892)
Requirement already up-to-date: nitime in /usr/local/lib/python3.6/dist-packages (from brainiak==0.11.dev9+g7614892)
Requirement already up-to-date: numpy!=1.17.* in /usr/local/lib/python3.6/dist-packages (from brainiak==0.11.dev9+g7614892)
Requirement already up-to-date: scikit-learn[alldeps]>=0.18 in /usr/local/lib/python3.6/dist-pa

### Dataset <a id="data-set"></a> 

For this script we will use the face/scene dataset from [Wang et al. (2015)](https://doi.org/10.1016/j.jneumeth.2015.05.012), who in turn used localizer data from [Turk-Browne et al. (2012)](https://doi.org/10.1523/JNEUROSCI.0942-12.2012).

Localizer details from Turk-Browne et al. (2012):

"Subjects also completed a functional localizer run lasting 6 min 6 s [...] The localizer run alternated between six repetitions each of scene and face blocks (Turk-Browne et al., 2010). Blocks contained 12 stimuli presented for 500 ms every 1500 ms. The 18 s of stimulation was followed by 12 s of fixation before the next block. Subjects made the same indoor/outdoor judgment for scenes, and a male/female judgment for faces."

**Self-study:** Explore the data

## 1. Searchlight workflow <a id="sl_wf"></a>

Running a searchlight is computationally intensive, complex and involves many steps. To show how the searchlight functionality in BrainIAK works, we will walk through the steps needed to perform a simple searchlight that can be run in this notebook before moving onto a real example that requires submitting the job to a cluster. This simple workflow takes the following steps:

>1. [Data preparation](#data_prep)
>2. [Set the searchlight parameters](#set_param)
>3. [Create the searchlight object](#create_obj)
>4. [Create our classification kernel](#create_kernel)
>5. [Execute the searchlight](#exec_sl)


However, before we start, there are a few things that you should know about searchlights. Think of a searchlight as a processing step in which you pull out a certain size chunk of your data and then perform a kernel operation (specified by a function you write). You can use any kernel on this chunk of data interchangeably. Critically, **the searchlight function does not specify the analysis you want to perform, all it does is carve up the data.**

**Computational demand and parallelization**

As mentioned before, searchlights are computationally intensive and so we need to be aware of what kind of burden they might impose. With each subject, we want to perform the operation thousands of times (once for each of their brain voxels). If we were to run this serially, even if each operation only took 1 s to complete, the analysis would take multiple days for only one participant. With nested cross-validation or other recursive steps, the full analysis could take months or years (and you'd lose a lot of points on your assignment).

Fortunately, the searchlight function in [BrainIAK](http://brainiak.org/) intelligently parallelizes your data to give you a considerable and scalable speed boost. Parallelization is the idea that when two or more computational tasks can be completed independently (because they don't interact in any way) then it is possible to run these tasks simultaneously on different cores. Note that we refer to cores as our unit of serial processing, although there are other parallelizations available within-core, such as threads or even multiple instructions within thread. The nice thing about parallelization is that it is scalable: in general, a job parallelized across 10 cores will run up to 10 times faster than on one core. For reference, your computer likely has 2, 4, or more cores, so you could speed up processing if you recruited all of these resources (and shut down all other types of background processing). 
<div class="alert alert-block alert-info">
So remember, the two main things that determine the speed of a searchlight: the **kernel algorithm** and the **amount of parallelization**.
</div>

**How does the BrainIAK searchlight work?**

To analyze data efficiently, it is important to understand how the Searchlight function in [BrainIAK](http://brainiak.org/) works. You must provide the function with a numpy volume of 4D data and a binary mask of brain voxels. The searchlight code simply searches for every voxel in the mask that is equal to 1 and then centers a searchlight around this. This means that for every value of 1 in your mask, the searchlight function will apply your kernel function to the corresponding voxel (and those around it) in the 4D volume. Hence when writing the kernel you need to keep in mind that the input data the function receives are not the size of the original data but instead the size of the searchlight radius. In other words, you might give the searchlight function a brain and mask volume that is 64x64x64 but each kernel operation only runs on a data and mask volume that is 3x3x3 (or whatever your searchlight radius is). As per the logic of searchlights, the center of each mask in the searchlight will be equal to 1 (otherwise the searchlight wouldn't have selected it). 

**How to start using a searchlight? Small!**

When getting used to searchlights it is encouraged that you scale up your code gently. This is to prevent the possibility that you run a searchlight that takes a very long time to finish only to find there was a small error (which happens a lot). Instead it is better to write a simple function that runs quickly so you can check if your code works properly before scaling up. A simple workflow for testing your searchlight (and estimating how long your searchlight would take on a bigger dataset) would be this:

1. Create a mask of one voxel and run the searchlight interactively (like we are doing now, using a notebook) to check whether the code works.
2. Use timestamps to extract the execution time  
3. Print the number of voxels that are passed to the searchlight function  
4. Run the searchlight as a job on the smallest unit of real data you have (a single run or single participant)
5. Check the runtime and memory usage of this searchlight (e.g. on slurm: `sacct -j $JID --format=jobid,maxvmsize,elapsed`).  

Taking our own advice, we are going to write a searchlight script below to perform a very simple searchlight. In fact we are only going to run this searchlight on one voxel in the brain so that we can see whether our code is working and how long each kernel operation would take. After we have familiarized ourselves with the way searchlights work on a small scale, we will then graduate to full-scale analyses using batch scripts and cluster computing.

## 1.1 Data preparation <a id="data_prep"></a>
Prepare a single participant using a similar pipeline to what we have developed previously. The critical change needed here is the shape of the data: In the past we wanted a time x voxel matrix, but the input to a searchlight is a 4D volume (brain x, y, z, time t), hence we need to add a step, as below.

<a id="ex1"></a>
**Exercise 1:** Why does the input to a searchlight analysis need to be 4D rather than 2D? 

**A:**

In [57]:
import h5py
import warnings
import sys 
if not sys.warnoptions:
    warnings.simplefilter("ignore")
    
# Import libraries
import nibabel as nib
import numpy as np
import os 
import time
from nilearn import plotting
from brainiak.searchlight.searchlight import Searchlight
from brainiak.fcma.preprocessing import prepare_searchlight_mvpa_data
from brainiak import io
from brainiak import image
from pathlib import Path
from shutil import copyfile
from nilearn.input_data import NiftiMasker, NiftiLabelsMasker

# Import machine learning libraries
from sklearn.model_selection import StratifiedKFold, GridSearchCV, cross_val_score
from sklearn.svm import SVC
import scipy.stats

import matplotlib.pyplot as plt

# Set printing precision
np.set_printoptions(precision=2, suppress=True)

%matplotlib inline
%matplotlib notebook
%autosave 5
sns.set(style = 'white', context='poster', rc={"lines.linewidth": 2.5})
sns.set(palette="colorblind")

Autosaving every 5 seconds


### 1.1.1 Helper functions <a id="helper"> </a>

To make it easy for you to achieve the main goals of this notebook, we have created helper functions that perform data extraction from nifti files data, format them into arrays, and prepares the data for the searchlight function.

### 1.1.2 Create a directory structure<a id="helper"> </a>

We strongly recommend storing the data and results generated by the analysis in separate directories from the raw data (here we have enforced this by making the raw data directory read-only). On clusters these kinds of intermediate products should be stored on high-speed `scratch` disks. Typically, once your analysis is finished, you would copy the results and any important intermediate steps back to more permanent storage like your home directory or a project directory.

<div class="alert alert-block alert-warning">
Just like a whiteboard is wiped regularly, scratch storage is typically erased after a month or two. Moreover, scratch space is not backed up, so you could commit your work regularly, at a minimum after every session.
</div>

Please specify the path to a useable `scratch` folder:

<a id="ex2"></a>
**Exercise 2.** Print out the labels for one subject to get an understanding of the stimulus presentation.


## 1.2 Executing the searchlight workflow<a id="exe_wf"></a>
### 1.2.1 Set searchlight parameters <a id="set_param"></a>

To run the [searchlight](http://brainiak.org/docs/brainiak.searchlight.html) function in BrainIAK you need the following parameters:  

1. **data** = The brain data as a 4D volume.  
2. **mask** = A binary mask specifying the "center" voxels in the brain around which you want to perform searchlight analyses. A searchlight will be drawn around every voxel with the value of 1. Hence, if you chose to use the wholebrain mask as the mask for the searchlight procedure, the searchlight may include voxels outside of your mask when the "center" voxel is at the border of the mask. It is up to you to decide whether then to include these results.  
3. **bcvar** = An additional variable which can be a list, numpy array, dictionary, etc. you want to use in your searchlight kernel. For instance you might want the condition labels so that you can determine to which condition each 3D volume corresponds. If you don't need to broadcast anything, e.g, when doing RSA, set this to 'None'.  
4. **sl_rad** = The size of the searchlight's radius, excluding the center voxel. This means the total volume size of the searchlight, if using a cube, is defined as: ((2 * sl_rad) + 1) ^ 3.  
5. **max_blk_edge** = When the searchlight function carves the data up into chunks, it doesn't distribute only a single searchlight's worth of data. Instead, it creates a block of data, with the edge length specified by this variable, which determines the number of searchlights to run within a job.  
6. **pool_size** = Maximum number of cores running on a block (typically 1).  

<a id="ex2"></a>
**Exercise 2:** Searchlights don't need to be cubes. What other shape(s) does BrainIAK support and how do you specify this?

**A:**

### 1.2.2 Create Searchlight Object  <a id="create_obj"></a>

### 1.2.3 Define the function (a.k.a. "kernel") that needs to be computed <a id="create_kernel"></a>

For every searchlight you need a function to run in the searchlight. This is the function that you want to measure/classify your data with. This could perform classification, RSA, or any other computation that you wish.

**NB.** The word "kernel" is used in multiple mathematical/computational contexts. In this notebook we use kernel to represent the function that is passed to the searchlight object.

### 1.2.4 Execute the searchlight <a id="exec_sl"></a>

We execute the searchlight and save the results in brain space. Each searchlight result is assigned to the voxel that the searchlight is centered on. This array is then saved to a nifti volume using the following:

> `nib.Nifti1Image`: Created a nifti volume with the same size and in the same space (e.g. MNI) as the subject data.  
> `.header`: This gets header information from the subject data.  
> `.set_zooms`: Sets the voxel dimensions e.g 1.5mm x 1.5mm x 1.5mm.  


<a id="ex3"></a>
**Exercise 3:** What would setting `sl_rad` to 3 do? (Please still use `sl_rad = 1` in the following exercises, we just want you to state the answer.)

**A:**

<a id="ex4"></a>
**Exercise 4:** Estimate how long it would take to run the searchlight analysis above on the whole brain, using the same parameters.

**A:**

<a id="ex5"></a>
**Exercise 5:** Modify the ``small_mask`` variable to select a 4x4x4 sub-volume of 64 voxels (as the searchlight centers) around the voxel in the example above. Hint: You do not need to change the ``sl_rad`` variable.

<a id="ex6"></a>
**Exercise 6:** Modify the calc_svm function to run only if there are at least 14 "brain" voxels from the mask in the 27-voxel searchlight centered on each of these 64 voxels, otherwise return -1. This could be useful if you wanted to ignore searchlights near the edge of the brain. 

<a id="ex7"></a>
**Exercise 7:** Modify this new calc_svm function to additionally perform nested cross-validation (use the code you made for the notebook on classification) over different cost parameters of the linear SVM kernel. Note that we do not have ``run_ids`` as in the previous notebooks, so you should use the [StratifiedKFold](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html) to perform the cross-validation.

**Visualizing the data**

As you have seen, the output of the searchlight analysis is a 3D volume with the outputs of your kernel for each voxel it was centered on. The [nilearn package](http://nilearn.github.io/plotting/index.html) has multiple plotting options to allow you to view your data within python. This is good for quick visualizations but can be buggy and is not great for exploration. You can also view the data in other packages such as FSL or AFNI. If you followed the steps above, you likely won't see many bright spots because we only ran the searchlight in a tiny part of the brain. But if you look at the data in fslview and change the coordinates to X=30, Y=31, Z=13 you should see a non-zero value.

## 1.3 Executing on multiple subjects <a id="multi_subj"></a>

So far we have loaded data for one subject and performed within-subject analysis, similar to what we have done in notebooks 1-5 (but in standard MNI space). You can also perform searchlight analysis on a group of subjects. This requires making a list of subjects.

In [8]:
path = '/content/'
all_bold_vol = np.load(path+'bold_data_games.npy')
# bold_vol = all_bold_vol[:,:,0]

# load mask and get voxel coordinates
mask_arr = np.load(path+'mask_arr.npy') # all masks are the same
mask_mat = mask_arr[0] # so we can pick any one from the array
coords_mat = np.array(np.where(mask_mat == 1)) # so need one set of voxel coordinates for all
coords_mat[[0, 2]] = coords_mat[[2, 0]] # exchange the rows
print(coords_mat.shape) #coords_mat contains voxel coordinates of brain region voxels

# mask_nii is the functional mask, this selects the brain voxels
mask_nii = nib.load(os.path.join(path, 'mask.nii')) 
print(mask_nii.shape)
# we get the brain mask (boolean array) with the .dataobj method
# brain_mask contains all voxels, 1 at brain regions
# coords_mat can be used to index into brain_mask 
brain_mask = np.array(mask_nii.dataobj)
print(brain_mask.shape)
affine_mat = mask_nii.affine
dimsize = mask_nii.header.get_zooms()

# Get the list of nonzero voxel coordinates from the nii mask. SAME AS coords_mat
coords_nii = np.where(brain_mask)
print(coords_nii[0])
print(coords_mat[0])
# cords_nii corresponds to the bold_vol <=> verify with Daphne

# this where we plot our mask ON (sometimes called brain_nii) - the anatomical/structural image
mean_nii = nib.load(os.path.join(path, 'mean.nii')) 

(3, 220075)
(79, 95, 79)
(79, 95, 79)
[ 2  3  3 ... 74 74 74]
[39 40 36 ... 34 35 44]


In [9]:
behavior_RDM = np.load(path+'behavior_RDM.npy')
print(behavior_RDM)
behavior_RDM = np.tril(behavior_RDM,-1).ravel()
behavior_RDM = behavior_RDM[behavior_RDM != 0]
print(behavior_RDM)

[[0.   0.59 0.55 0.51 0.47 0.36]
 [0.59 0.   0.63 0.51 0.51 0.51]
 [0.55 0.63 0.   0.57 0.47 0.47]
 [0.51 0.51 0.57 0.   0.5  0.43]
 [0.47 0.51 0.47 0.5  0.   0.64]
 [0.36 0.51 0.47 0.43 0.64 0.  ]]
[0.59 0.55 0.63 0.51 0.51 0.57 0.47 0.51 0.47 0.5  0.36 0.51 0.47 0.43
 0.64]


In [62]:
coords = tuple(coords_mat)
small_mask = np.zeros(brain_mask.shape)
small_mask[coords] = 1
# small_mask[42, 28, 26] = 1
print(np.where(small_mask))
vol4D = mask_nii.shape+(6,)

# For 8 subjects
all_bold = []
for sub_id in range(8):
    isc_vol = np.zeros(vol4D)
    bold_vol = all_bold_vol[:,:,sub_id]
    for i in range(6):
        for j in range(len(coords[0])):
            isc_vol[(coords[0][j], coords[1][j], coords[2][j], i)] = bold_vol[i][j]
    all_bold.append(isc_vol)

# Preset the variables
data = all_bold
mask = small_mask
bcvar = behavior_RDM
sl_rad = 5
max_blk_edge = 5
pool_size = 1




(array([ 2,  3,  3, ..., 74, 74, 74]), array([43, 42, 43, ..., 45, 47, 51]), array([32, 31, 32, ..., 31, 26, 26]))
Setup searchlight inputs
Number of subjects: 8
Input data shape: (79, 95, 79, 6)
Input mask shape: (79, 95, 79)



In [70]:
sl_rad = 3
# Start the clock to time searchlight
begin_time = time.time()

# Create the searchlight object
sl = Searchlight(sl_rad=sl_rad,max_blk_edge=max_blk_edge)
print("Setup searchlight inputs")
print("Number of subjects: " + str(len(data)))
print("Input data shape: " + str(data[0].shape))
print("Input mask shape: " + str(mask.shape) + "\n")

# Distribute the information to the searchlights (preparing it to run)
sl.distribute(data, mask)
# Data that is needed for all searchlights is sent to all cores via the sl.broadcast function. 
#In this example, we are sending the labels for classification to all searchlights.
sl.broadcast(bcvar)

Setup searchlight inputs
Number of subjects: 8
Input data shape: (79, 95, 79, 6)
Input mask shape: (79, 95, 79)



In [71]:

# Set up the kernel, RDM analysis
def rdm_all(data, sl_mask, myrad, bcvar):
    all_rho = []
    behavior_RDM = bcvar
    # Loop over subject: 
    for idx in range(len(data)):
        data4D = data[idx]
        bolddata_sl = data4D.reshape(sl_mask.shape[0] * sl_mask.shape[1] * sl_mask.shape[2], data[0].shape[3]).T
        neural_RDM = np.tril(1-np.corrcoef(bolddata_sl), -1)
        neural_RDM = neural_RDM.ravel()
        neural_RDM = neural_RDM[neural_RDM != 0]
        subject_spearman = scipy.stats.spearmanr(neural_RDM, behavior_RDM,axis=None)
        all_rho.append(subject_spearman.correlation)
    tstats,p = scipy.stats.ttest_1samp(np.arctanh(all_rho), popmean=0)
    return (tstats, p)

# Execute searchlight on 8 subjects
print("Begin Searchlight\n")
sl_result_allsubj = sl.run_searchlight(rdm_all, pool_size=pool_size)
print("End Searchlight\n")
print(sl_result_allsubj[mask==1])

Begin Searchlight

End Searchlight

[None (-0.10951345066840651, 0.9158686517461855)
 (-0.36733116315278297, 0.7242260808710574) ...
 (0.7420961754191298, 0.4821812437603141)
 (-0.055390022926200745, 0.9573755369719533)
 (0.09709537592823557, 0.9253722009805174)]


In [72]:
print(sl_result_allsubj.shape, sl_result_allsubj[coords].shape)
print(sl_result_allsubj[coords])
brain_results = sl_result_allsubj[coords]
all_rho = []
all_pvalues = []
for i in range(len(brain_results)):
    if brain_results[i] is not None:
        all_rho.append(brain_results[i][0].astype('double'))
        all_pvalues.append(brain_results[i][1].astype('double'))
    else:
        all_rho.append(0)
        all_pvalues.append(1)
print(len(all_rho))
print(len(all_pvalues))

(79, 95, 79) (220075,)
[None None None ... None None None]
220075
220075


In [73]:

np.save(path+'pvalues_all', all_pvalues)
np.save(path+'tstats_all', all_rho)

In [65]:
from nilearn import plotting
# Save the results to a .nii file
# output_name = os.path.join(path, ('allsubj_result.nii.gz'))
# sl_nii = nib.Nifti1Image(all_rho, affine_mat, mask_nii.header)  # create the volume image
# hdr = sl_nii.header  # get a handle of the .nii file's header
# hdr.set_zooms((dimsize[0], dimsize[1], dimsize[2]))
# nib.save(sl_nii, output_name)  # Save the volume
tstats=all_rho
pvalues=np.array(all_pvalues).transpose()
brain_nii=mean_nii
theta=0.1
cut_coords=[36, -44, -16]
vmax=12
# 1) create a volume from mask_nii
isc_vol = np.zeros(mask_nii.shape) 

print(f'Display t statistics with a corresponding p < {theta}')

# use theta to select the t statistics to plot
# make arr to store the t stats with p < theta
sig_arr = np.zeros(pvalues.shape)

# get p indices smaller or equal to theta
theta_indices = np.where(pvalues < theta)
print(theta_indices[0])

# get the t stats at these indices
selected_tstats = np.array(tstats)[theta_indices[0]
                                   ]

# map the selected t statistics on the right places
sig_arr[theta_indices] = selected_tstats

# 2) Map the t statistics in voxel space
isc_vol[coords] = sig_arr

# 3) Create a nifti image from this with the affine from mask_nii
isc_nifti = nib.Nifti1Image(isc_vol, mask_nii.affine, mask_nii.header)

f, ax = plt.subplots(1,1, figsize = (12, 5), dpi=90)
plotting.plot_stat_map(
    stat_map_img=isc_nifti, 
    bg_img=brain_nii,
    axes=ax,
    black_bg=True,
    cut_coords=cut_coords,
    vmax=vmax
);
print("here")
ax.set_title(f't map with threshold p < {theta}'); 
plt.show()

Display t statistics with a corresponding p < 0.1
[   723    737    766 ... 218177 218207 218485]


<IPython.core.display.Javascript object>

here


**Sanity Check:**

To make sure that each subject is being processed correctly, we can compare the results by loading one subject alone vs. loading the same subject amongst three subjects.

## 2. Running searchlight analyses on a cluster<a name="submitting_searchlights"></a>

**Note: If you are running this section in a non-cluster environment (e.g., a laptop or a server with limited resources), the run-tine for this section can be quite long. You can make an estimate of the run-time (see [exercise 4](#ex4) above) and plan accordingly.**

Running searchlight analyses through notebooks or interactive sessions isn't tractable for real studies. Although the example above ran quickly and without parallelization, we only performed 64 analyses. We are now going to write a script to run a searchlight as a "batch" job. To learn how to submit jobs, you need to know a bit about [slurm](https://research.computing.yale.edu/support/hpc/user-guide/slurm), the scheduling system we assume you are using. If you are using a different scheduler you will need to follow different instructions. 

To run a job, a good work flow is to have two scripts: One script that actually does the computation you care about (e.g., a python script like utils.py) and a bash script that sets up the environment and specifies the job parameters. The environment refers to the modules and packages you need to run your job. The job parameters refer to the partition you are going to use (-p), the number of cores (-n), the amount of memory (-m) and required time (-t). To run your job you then call the bash script with something like: 'sbatch script.sh'

**Self-study:** Lucky for you we have already written the script needed here, called `run_searchlight.sh`. This script is written in the bash command language. Please explore this script to get familiar with submitting jobs. It will be very useful for future analyses to customize it for your needs (using a text editor like nano or nedit).

In [ ]:
# Print the bash script for running searchlights
!cat 07-searchlight/run_searchlight.sh

When a job starts, a log file named as ``searchlight-%j.out`` is automatically created in the same directory as your shell script. You can see any output from your script printed into the log file. You can print out the content of the log file in the terminal or open it using a text editor to help debug your code. To check the status of your job you should use `squeue -u $USER`. Sometimes your jobs won't run immediately because they are waiting in the queue. Conversely, don't submit too many jobs or your classmates won't be able to run theirs.

## 2.1 Distributing jobs with parallel computing<a name="ranks"></a>

When you parallelize an analysis across multiple cores, this typically means that each core will run the code independently (though there are ways for cores to communicate directly with each other). This means you will load in all of the data on each core. The searchlight function then notices that there are multiple cores running the same job and assigns different pieces of the data to each core for analysis. The message passing interface (MPI), the parallelizing framework used by BrainIAK and most high-performance computing applications, keeps track of each process by assigning it a rank, starting at 0. We provide a brief overview of ranks, cores, and nodes below.

<img src="https://github.com/brainiak/brainiak-tutorials/blob/master/tutorials/imgs/lab7/nodes_process.jpg?raw=1" width="300" height="300"/>


What is a rank? It is a process generated by the application that you are running. In the above figure "Process 1" can be considered to be rank=0 and "Process 2" rank=1. A rank can use more than one core on the cluster and is managed by MPI. Each rank also uses a part of the memory allocated. The cores and memory are part of the hardware belonging to a "node". A node is akin to a server. When you submit a job, you are requesting use of part of the node, or sometimes even the entire node. **Optimizing the memory, and number of cores for your batch job will lead to significant gains in run-time for your programs**.

MPI handles all communication between the ranks (or processes). This can occur within a single node, or if you have asked for lots of resources, this can even span multiple nodes. Each process can spawn multiple threads, and Open-MP handles communication between threads.


<img src="https://github.com/brainiak/brainiak-tutorials/blob/master/tutorials/imgs/lab7/mpi_openmp.jpg?raw=1" width="300" height="300"/>


**You do not need to configure any of the above. BrainIAK handles all the parallelization for you.** Just make sure that you have requested the appropriate number of cores and the memory for your job.


 
If you are running an analysis across 2 cores then some of your computations will be run with rank=0 and some with rank=1. The following commands are used to access MPI information that your job needs.

```
comm = MPI.COMM_WORLD
rank = comm.rank
size = comm.size
```

For efficient utilization of memory, we typically load the data on as few ranks as possible. If memory is sufficient to load all data on one rank, then we would write someting like this:
```
if rank==0:
    load all my data
else:
    load labels for all subject
    load the mask
distribute(pieces of my data to other ranks)
run searchlight
```

The above will avoid loading every subjects data on every rank. **The labels and mask must be loaded on all ranks.** The distribution will allocate only pieces of the data for processing. Again, this is all handled by MPI. In searchlight, the `sl.distribute` methods handles the distribution to different ranks.

After the searchlights have all finished, you need to save the data. MPI gathers the results from all of the cores and BrainIAK saves the results.  



In [ ]:
# Example of loading data only one rank.
from mpi4py import MPI
comm = MPI.COMM_WORLD
rank = comm.rank
size = comm.size

sub_id = 1
# Load data only on rank==0
if rank==0:
    bold_vol, labels, whole_brain_mask, affine_mat, dimsize = load_fs_data(data_path, sub_id)
    data = bold_vol
else:
    data = None
    
# Make a mask of only one arbitrary voxel
small_mask = np.zeros(whole_brain_mask.shape)
small_mask[28:32, 29:33, 11:15] = 1

# Preset the variables

mask = small_mask
bcvar = labels
sl_rad = 1
max_blk_edge = 5
pool_size = 1


# Start the clock to time searchlight
begin_time = time.time()

# Create the searchlight object
sl = Searchlight(sl_rad=sl_rad,max_blk_edge=max_blk_edge)
print("Setup searchlight inputs")
print("Input data shape: " + str(data.shape))
print("Input mask shape: " + str(mask.shape) + "\n")

# Distribute the information to the searchlights (preparing it to run)
sl.distribute([data], mask)

# Data that is needed for all searchlights is sent to all cores via the sl.broadcast function. In this example, we are sending the labels for classification to all searchlights.
sl.broadcast(bcvar)

# Set up the kernel, in this case an SVM
def calc_svm(data, sl_mask, myrad, bcvar):  
    if np.sum(sl_mask) < 14:
        return -1
    # Pull out the data
    data4D = data[0]
    labels = bcvar    
    bolddata_sl = data4D.reshape(sl_mask.shape[0] * sl_mask.shape[1] * sl_mask.shape[2], data[0].shape[3]).T    
    t1 = time.time()
    scores = []
    # outer loop
    sp = StratifiedKFold(n_splits=3)
    for train, test in sp.split(bolddata_sl, labels):
        train_data = bolddata_sl[train, :]
        test_data = bolddata_sl[test, :]
        train_label = labels[train]
        test_label = labels[test]     
        # inner loop
        sp_train = StratifiedKFold(n_splits=2)
        parameters = {'C':[0.01, 0.1, 1, 10]}
        inner_clf = GridSearchCV(
            SVC(kernel='linear'),
            parameters,
            cv=sp_train,
            return_train_score=True)
        inner_clf.fit(train_data, train_label)
        # best C from inner loop
        C_best = inner_clf.best_params_['C'] 
        # Train in outer loop
        clf = SVC(kernel='linear', C=C_best)
        clf.fit(train_data, train_label)
        # Test in outer loop
        scores.append(clf.score(test_data, test_label))
    accuracy = np.mean(scores)
    t2 = time.time()    
#     print('Kernel duration: ' + str(t2 - t1) + "\n\n")
    return accuracy

print("Begin SearchLight\n")
sl_result = sl.run_searchlight(calc_svm, pool_size=pool_size)
print("End SearchLight\n")

end_time = time.time()

# Print outputs
print("Summarize searchlight results")
print("Number of searchlights run: " + str(len(sl_result[mask==1])))
print("Accuracy for each kernel function: " + str(sl_result[mask==1].astype('double')))
print('Total searchlight duration (including start up time): %.2f' % (end_time - begin_time))


We have written a Python script for running searchlights. The file *searchlight.py* loads in number of participants, sets up the searchlight and kernel and then performs the searchlight across the multiple cores that the code is run on. 

This code performs leave-one-subject-out cross validation (i.e., the testing accuracy of subject 1 is based on the SVM classifier trained on subject 2 and 3; accuracy of subject 2 is based on the SVM trained on subject 1 and 3, etc.) The reason we are doing this cross-validation is that the single subject case as in the previous sections in this notebook is a case of double dipping. We only have one run of data for each subject, so the z-scoring within subject will cause double dipping in the single subject case.

These results are saved for each subject separately. 

**Exercise 10:**  <a id="ex10"></a> Run the `run_searchlight.sh` script using `sbatch run_searchlight.sh` in the command line. Once your analysis has finished (should take ~6 mins), load in your averaged searchlight results and plot it with the imported function [plotting](http://nilearn.github.io/modules/reference.html#module-nilearn.plotting) from nilearn. You will find function [plotting.plot_stat_map](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_stat_map.html) useful. However, be aware that some of these functions assume the brain is MNI space. This face-scene dataset is not in MNI space, so if you overlay it on the default background the image will be 'outside of the brain'. To visualize this correctly, also provide the image as `bg_img` into this function. Also load in the averaged searchlight results across all 18 subjects we computed for you and plot it. The file is in the same directory as this notebook, called 'avg18_whole_brain_SL.nii.gz'. Use the same 'cut_coords', 'threshold', and 'vmax' across these two plots. You can start from threshold=0.65, cut_coords=(50,-40,10), vmax=1 for a good visualization. Compare the two plots. 

**Exercise 11:**  <a id="ex11"></a> From your results, what do you infer about the discriminability of faces vs. scenes. Is it localized to a particular brain region?

 <a id="ex12"></a>
**Exercise 12:** How do you figure out which searchlight cube is running on which rank when you run it on cluster? Write a searchlight_rank.py script to figure this out. Rewrite the kernel to return rank instead of accuracy and save the brain map as a nifty file. Run this on one subject only.

**Novel contribution:**<a name="novel"></a> be creative and make one new discovery by adding an analysis, visualization, or optimization.

Some ideas for novel contribution:  
- Change the kernel to RSA and correlate it with a model RDM that distinguishes faces and scenes. Compare the RSA results with the decoding results.
- Compute the confusion matrix for each searchlight. You can find useful information about confusion matrix [here](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html).
- Run a searchlight, but not on every voxel. Run searchlights only on every third voxel, whole brain.
- Run each subject on a different rank. BrainIAK searchlight has a way to do that.
- Visualize the accuracy map using surface mapping.

## Contributions <a id="contributions"></a> 

M. Kumar, C. Ellis and N. Turk-Browne produced the initial notebook 03/2018  
T. Meissner minor edits  
H. Zhang preprocessed dataset, add multi-subject section, add multiple exercises, add solutions, other edits  
Vineet Bansal provided the MPI diagrams.  
David Turner provided extensive input on how to use MPI for efficient running of jobs.  
M. Kumar added MPI information and enhanced section contents.  
K.A. Norman provided suggestions on the overall content and made edits to this notebook.  
C. Ellis implemented updates from cmhn-s19.<br/>
X. Li changed nipype function get_data() to get_fdata() since get_data() is deprecated in section 1.1.1